---
- name: Create Sentry Project
  hosts: all
  become: yes
  vars:
    - sentry_api_key: "{{ SENTRY_API_KEY }}"
    - sentry_organization_slug: "{{ SENTRY_ORGANIZATION_SLUG }}"
    - sentry_team_slug: "{{ SENTRY_TEAM_SLUG }}"
    - project_name: "{{ PROJECT_NAME }}"
    - service_name: "{{ SERVICE_NAME }}"
    - platform: "{{ PLATFORM }}"
  tasks:
    - name: Create sentry project
      uri:
        url: "https://sentry.io/api/0/teams/{{ sentry_organization_slug }}/{{ sentry_team_slug }}/projects/"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ sentry_api_key }}"
        body:
          name: "{{ project_name }}_{{ service_name }}"
          slug: "{{ project_name }}_{{ service_name }}"
          platform: "{{ platform }}"
        status_code: 200, 201
      # loop:
      #   - { name: "backend", platform: "node" }
      #   - { name: "frontend", platform: "javascript-react" }

    - name: Get sentry project DSN key
      uri:
        url: "https://sentry.io/api/0/projects/{{ sentry_organization_slug }}/{{ project_name }}_{{ service_name }}/keys/"
        method: GET
        headers:
          Authorization: "Bearer {{ sentry_api_key }}"
      register: project_dsn

    - name: Save sentry project DSN keys to sentry.env files
      copy:
        content: "{{ project_dsn.json[0].dsn.secret }}"
        dest: "/home/code/{{ service_name }}_sentry_dsn.env"
        mode: 0600

    - name: Copy sentry project DSN key file to local
      fetch:
        src: "/home/code/{{ service_name }}_sentry_dsn.env"
        dest: "./"
        flat: yes
