---
- name: Fill Backend secrets in GitHub
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
    - portainer_url: "{{ PORTAINER_URL }}"
    - service_url: "{{ SERVICE_URL }}"
  tasks:
    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent

    - name: Create github-node-api directory
      file:
        path: "/home/code/github-node-api"
        state: directory

    - name: Fill github-node-api directory from local
      copy:
        src: "{{ playbook_dir }}/../github/github-node-api/{{ item }}"
        dest: "/home/code/github-node-api/{{ item }}"
      loop:
        - create_secret.js
        - package.json

    - name: Install dependencies
      shell:
        cmd: "npm install"
        chdir: "/home/code/github-node-api"

    - name: Get Portainer backend webhook token
      shell:
        cmd: "cat /home/code/backend_webhook_token"
      register: backend_webhook_token

    - name: Set secrets to GitHub
      no_log: true
      shell:
        cmd: "node ./create_secret.js {{ github_token }} {{ github_repository }} {{ item.secret_name }} {{ item.secret_content }} {{ item.secret_scope }}"
        chdir: "/home/code/github-node-api"
      loop:
        - {
            secret_name: PORTAINER_BACKEND_UPDATE_URL,
            secret_content: "https://{{ portainer_url }}/api/webhooks/{{ backend_webhook_token.stdout }}",
            secret_scope: actions,
          }
        - {
            secret_name: NEXT_PUBLIC_BACKEND_URL,
            secret_content: "https://{{ service_url }}",
            secret_scope: actions,
          }

    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent
