name: Ansible

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string

jobs:
  ansible:
    timeout-minutes: 60
    name: ansible run script
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/ansible
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set script file name
        id: set-script-file-name
        run: echo "SCRIPT_FILE_NAME=$(echo ${{ github.ref_name }} | cut -d'-' -f2)" >> $GITHUB_OUTPUT
      - name: Set script args
        id: set-script-args
        run: echo "ARGS=$(echo ${{ github.ref_name }} | cut -d'-' -f3- | tr '-' ' ')" >> $GITHUB_OUTPUT
      - name: Script and args
        run: |
          echo SCRIPT: ${{ steps.set-script-file-name.outputs.SCRIPT_FILE_NAME }}.sh
          echo ARGS: ${{ steps.set-script-args.outputs.ARGS }}
      - name: Create inventory file
        run: |
          cp ./actions/inventory.yaml.example inventory.yaml
      - name: Replace ANSIBLE_HOST in inventory.yaml
        run: |
          sed -ie "s/ANSIBLE_HOST/${{ secrets.ANSIBLE_HOST }}/g" inventory.yaml
      - name: Replace ANSIBLE_PASSWORD in inventory.yaml
        run: |
          sed -ie "s/ANSIBLE_PASSWORD/${{ secrets.ANSIBLE_PASSWORD }}/g" inventory.yaml
      - name: Add deployer secrets to env file
        run: |
          secrets=(\
            "PROJECT_NAME ${{ secrets.PROJECT_NAME }}"\
            "DOCKER_HUB_USERNAME ${{ secrets.DOCKER_HUB_USERNAME }}"\
            "DOCKER_HUB_LOGIN_USERNAME ${{ secrets.DOCKER_HUB_LOGIN_USERNAME }}"\
            "DOCKER_HUB_URL ${{ secrets.DOCKER_HUB_URL }}"\
            "DOCKER_HUB_PASSWORD ${{ secrets.DOCKER_HUB_PASSWORD }}"\
            "ANSIBLE_HOST ${{ secrets.ANSIBLE_HOST }}"\
            "ANSIBLE_PASSWORD ${{ secrets.ANSIBLE_PASSWORD }}"\
            "ROOT_AWS_ACCESS_KEY ${{ secrets.ROOT_AWS_ACCESS_KEY }}"\
            "ROOT_AWS_SECRET_ACCESS_KEY ${{ secrets.ROOT_AWS_SECRET_ACCESS_KEY }}"\
            "ROOT_CLOUDFLARE_ACCOUNT_API_KEY ${{ secrets.ROOT_CLOUDFLARE_ACCOUNT_API_KEY }}"\
            "ROOT_CLOUDFLARE_ACCOUNT_EMAIL ${{ secrets.ROOT_CLOUDFLARE_ACCOUNT_EMAIL }}"\
            "ROOT_SENTRY_API_KEY ${{ secrets.ROOT_SENTRY_API_KEY }}"\
            "ROOT_SENTRY_ORGANIZATION_SLUG ${{ secrets.ROOT_SENTRY_ORGANIZATION_SLUG }}"\
            "ROOT_SENTRY_TEAM_SLUG ${{ secrets.ROOT_SENTRY_TEAM_SLUG }}"\
            "DOMAIN ${{ secrets.DOMAIN }}"\
            "JWT_SECRET ${{ secrets.JWT_SECRET }}"\
            "ADMIN_JWT_SECRET ${{ secrets.ADMIN_JWT_SECRET }}"\
            "APP_KEYS ${{ secrets.APP_KEYS }}"\
            "AWS_S3_BUCKET ${{ secrets.AWS_S3_BUCKET }}"\
            "AWS_S3_REGION ${{ secrets.AWS_S3_REGION }}"\
            "API_TOKEN_SALT ${{ secrets.API_TOKEN_SALT }}"\
            "SEED_ENTITES ${{ secrets.SEED_ENTITES }}"\
            "UPLOAD_PROVIDER ${{ secrets.UPLOAD_PROVIDER }}"\
            "DATABASE_NAME ${{ secrets.DATABASE_NAME }}"\
            "DATABASE_USERNAME ${{ secrets.DATABASE_USERNAME }}"\
            "DATABASE_PASSWORD ${{ secrets.DATABASE_PASSWORD }}"\
            "PORTAINER_USERNAME ${{ secrets.PORTAINER_USERNAME }}"\
            "PORTAINER_PASSWORD ${{ secrets.PORTAINER_PASSWORD }}"\
            "PORTAINER_SERVICE_SUBDOMAIN ${{ secrets.PORTAINER_SERVICE_SUBDOMAIN }}"\
            "TRAEFIK_USERNAME ${{ secrets.TRAEFIK_USERNAME }}"\
            "TRAEFIK_PASSWORD ${{ secrets.TRAEFIK_PASSWORD }}"\
            "TRAEFIK_SERVICE_SUBDOMAIN ${{ secrets.TRAEFIK_SERVICE_SUBDOMAIN }}"\
            "BACKEND_SERVICE_NAME ${{ secrets.BACKEND_SERVICE_NAME }}"\
            "BACKEND_SERVICE_SUBDOMAIN ${{ secrets.BACKEND_SERVICE_SUBDOMAIN }}"\
            "BACKEND_DOCKER_HUB_REPOSITORY_NAME ${{ secrets.BACKEND_DOCKER_HUB_REPOSITORY_NAME }}"\
            "FRONTEND_SERVICE_NAME ${{ secrets.FRONTEND_SERVICE_NAME }}"\
            "FRONTEND_SERVICE_SUBDOMAIN ${{ secrets.FRONTEND_SERVICE_SUBDOMAIN }}"\
            "FRONTEND_DOCKER_HUB_REPOSITORY_NAME ${{ secrets.FRONTEND_DOCKER_HUB_REPOSITORY_NAME }}"\
            "DOCUMENTATION_SERVICE_NAME ${{ secrets.DOCUMENTATION_SERVICE_NAME }}"\
            "DOCUMENTATION_SERVICE_SUBDOMAIN ${{ secrets.DOCUMENTATION_SERVICE_SUBDOMAIN }}"\
            "DOCUMENTATION_DOCKER_HUB_REPOSITORY_NAME ${{ secrets.DOCUMENTATION_DOCKER_HUB_REPOSITORY_NAME }}"\
            "GITHUB_TOKEN ${{ secrets.GH_TOKEN }}"\
            "GITHUB_REPOSITORY ${{ github.repository_owner }}/${{ github.event.repository.name }}"\
            "TELEGRAM_BOT_TOKEN ${{ secrets.TELEGRAM_BOT_TOKEN }}"\
            "RUN_TELEGRAM_BOT ${{ secrets.RUN_TELEGRAM_BOT }}"\
            "OPENAI_API_KEY ${{ secrets.OPENAI_API_KEY }}"\
            "STRIPE_API_KEY ${{ secrets.STRIPE_API_KEY }}"\
            "ZERO_X_PROCESSING_TEST_PAYMENTS ${{ secrets.ZERO_X_PROCESSING_TEST_PAYMENTS }}" \
            "ZERO_X_PROCESSING_SHOP_ID ${{ secrets.ZERO_X_PROCESSING_SHOP_ID }}" \
            "ZERO_X_PROCESSING_WEBHOOK_PASSWORD ${{ secrets.ZERO_X_PROCESSING_WEBHOOK_PASSWORD }}" \
          )

          for secret in "${secrets[@]}"; do
            secret_name=$(echo "$secret" | cut -d' ' -f1)
            secret_value=$(echo "$secret" | cut -d' ' -f2)

            echo "$secret_name=$secret_value" >> .env
          done
      # - name: Check env and inventory file
      #   run: |
      #     cat .env
      #     cat inventory.yaml
      - name: Make script file executable
        run: |
          chmod +x \
            ./$(echo ${{ github.ref_name }} | cut -d'-' -f2).sh
      - name: Run service script
        run: |
          ./$(echo ${{ github.ref_name }} | cut -d'-' -f2).sh $(echo ${{ github.ref_name }} | cut -d'-' -f3-)
