name: Update backend

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      PRERELEASE:
        required: true
        type: boolean

jobs:
  trigger-service-update:
    name: Run deployer
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook for staging service update
        if: ${{ inputs.PRERELEASE == true }}
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.STAGING_PORTAINER_BACKEND_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
      - name: Send webhook for production service update
        if: ${{ inputs.PRERELEASE == false }}
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PORTAINER_BACKEND_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
